### 1. 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123",
  "userRole": "USER"
}

### 2. 로그인 (토큰 발급)
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

> {%
    if (response.body && response.body.bearerToken) {
        client.global.set("accessToken", response.body.bearerToken)
    } else {
        client.global.set("accessToken", "")
    }
%}

### 3. POST /todos - 1
POST http://localhost:8080/todos
Content-Type: application/json
Authorization: {{accessToken}}

{
  "title": "Spring Boot 학습하기",
  "contents": "Spring Boot의 기본 개념과 REST API 개발 방법을 학습한다."
}

### 4. GET /todos - 1
GET http://localhost:8080/todos?page=1&size=10&weather=맑음&startAt=2000-10-31T01:30:00
Content-Type: application/json
Authorization: {{accessToken}}

### 5. POST /todos - 2
POST http://localhost:8080/todos
Content-Type: application/json
Authorization: {{accessToken}}

{
  "title": "Spring Boot 학습하기",
  "contents": "Spring Boot의 기본 개념과 REST API 개발 방법을 학습한다."
}

### 7. POST /commets - 1
POST http://localhost:8080/todos/1/comments
Content-Type: application/json
Authorization: {{accessToken}}

{
  "contents": "댓글 1"
}


### 7. POST /commets - 2
POST http://localhost:8080/todos/1/comments
Content-Type: application/json
Authorization: {{accessToken}}

{
  "contents": "댓글 2"
}

### 7. GET /commets
GET http://localhost:8080/todos/1/comments
Content-Type: application/json
Authorization: {{accessToken}}

### 8. GET /todos/{id}
GET http://localhost:8080/todos/1
Content-Type: application/json
Authorization: {{accessToken}}